In [8]:
import math
import itertools
import numpy as np
import multiprocessing
from multiprocessing import Process, Pool, Array
from tqdm import tqdm
import time
import matplotlib.pyplot as plt
import seaborn as sns; sns.set()

In [9]:
def probDist(a,b):
    c = 1 - (2*a+b)
    pArr = np.array([[a,a,b,c],
                 [a,c,a,b],
                 [b,a,c,a],
                 [c,b,a,a]])
    return pArr

In [10]:
def H(a):
    if(a == 0):
        return 0
    else:
        return (a*math.log2(1/a))

In [11]:
def mutualInfo(a,b):
    c = 1 - (2*a+b)
    return 2 - 2*H(a) - H(b) - H(c)

In [12]:
def calculateViolation(arr):
    x = np.arange(0.01, 1.01, 0.01)
    for a in x:
        for b in x:
            if(2*a+b<=1):
                pArr = probDist(a,b)
                xy = 0
                xY = 0
                Xy = 0
                XY = 0
                for i in range(0, arr.shape[1]):
                    xy += arr[i,0]*arr[i,2]*pArr[i,0]
                    xY += arr[i,0]*arr[i,3]*pArr[i,1]
                    Xy += arr[i,1]*arr[i,2]*pArr[i,2]
                    XY += arr[i,1]*arr[i,3]*pArr[i,3]
                E = xy + xY +Xy - XY
                MI = mutualInfo(a,b)
                if(abs(E) >= 3.9 and MI <= 0.5):
                    print("a = ", a, " b = ", b, " MI = ", MI, " E = ", abs(E))
                    print(arr)
                    print(" ")

In [13]:
values = [-1,1]
seq = itertools.product(values, repeat=16)
settingArrays = []
for s in seq:
    # convert to numpy array and reshape to 4x4
    settingArray = np.fromiter(s, np.int8).reshape(4, 4)
    settingArrays.append(settingArray)

In [14]:
p = Pool(multiprocessing.cpu_count())
p.map(calculateViolation, settingArrays)

a =  0.22  b =  0.55  MI =  0.4980415648642489  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [-1  1  1 -1]]
 
a =  0.23  b =  0.53  MI =  0.4727801509299966  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [-1  1  1 -1]]
 
a =  0.24000000000000002  b =  0.51  MI =  0.449862734976893  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [-1  1  1 -1]]
 
a =  0.25  b =  0.49  MI =  0.4292797287290896  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [-1  1  1 -1]]
 
a =  0.25  b =  0.5  MI =  0.5  E =  4.0
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [-1  1  1 -1]]
 
a =  0.26  b =  0.47000000000000003  MI =  0.4110292239471327  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [-1  1  1 -1]]
 
a =  0.26  b =  0.48000000000000004  MI =  0.4811544640047982  E =  4.0
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [-1  1  1 -1]]
 
a =  0.27  b =  0.45  MI =  0.3951169547419019  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [-1  1  1 -1]]
 
a =  0

[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.36000000000000004  b =  0.28  MI =  0.4245491894398694  E =  4.0
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.37  b =  0.25  MI =  0.3721033482343793  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.37  b =  0.26  MI =  0.43325362750738217  E =  4.0
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.38  b =  0.23  MI =  0.384987970335513  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.38  b =  0.24000000000000002  MI =  0.4449597206154776  E =  4.0
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.39  b =  0.21000000000000002  MI =  0.4011441997213686  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.39  b =  0.22  MI =  0.45983249703803447  E =  4.0
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.4  b =  0.19  MI =  0.42079251368944637  

[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.3  b =  0.39  MI =  0.3615850329466632  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.3  b =  0.4  MI =  0.42904940554533133  E =  4.0
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.31  b =  0.37  MI =  0.3552432679478492  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.31  b =  0.38  MI =  0.42195797777370025  E =  4.0
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.32  b =  0.35000000000000003  MI =  0.3513928661560136  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.32  b =  0.36000000000000004  MI =  0.4173168107445079  E =  4.0
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.33  b =  0.33  MI =  0.3500939883901443  E =  3.92
[[-1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.33  b =  0.34  MI =  0.41518129502697  E =  4.0
[[-1 -1 -

[[-1 -1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]
 [-1  1 -1  1]]
 
a =  0.22  b =  0.55  MI =  0.4980415648642489  E =  3.92
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]
 [ 1 -1  1 -1]]
 
a =  0.23  b =  0.53  MI =  0.4727801509299966  E =  3.92
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]
 [ 1 -1  1 -1]]
 
a =  0.24000000000000002  b =  0.51  MI =  0.449862734976893  E =  3.92
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]
 [ 1 -1  1 -1]]
 
a =  0.25  b =  0.49  MI =  0.4292797287290896  E =  3.92
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]
 [ 1 -1  1 -1]]
 
a =  0.25  b =  0.5  MI =  0.5  E =  4.0
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]
 [ 1 -1  1 -1]]
 
a =  0.26  b =  0.47000000000000003  MI =  0.4110292239471327  E =  3.92
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]
 [ 1 -1  1 -1]]
 
a =  0.26  b =  0.48000000000000004  MI =  0.4811544640047982  E =  4.0
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]
 [ 1 -1  1 -1]]
 
a =  0.27  b =  0.45  MI =  0.3951169547419019  E =  3.92
[[-1 -

 [-1  1 -1  1]]
 
a =  0.36000000000000004  b =  0.27  MI =  0.36230943684787736  E =  3.920000000000001
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.36000000000000004  b =  0.28  MI =  0.4245491894398694  E =  4.0
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.37  b =  0.25  MI =  0.3721033482343793  E =  3.92
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.37  b =  0.26  MI =  0.43325362750738217  E =  4.0
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.38  b =  0.23  MI =  0.384987970335513  E =  3.92
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.38  b =  0.24000000000000002  MI =  0.4449597206154776  E =  4.0
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.39  b =  0.21000000000000002  MI =  0.4011441997213686  E =  3.92
[[-1 -1  1  1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.39  b =  0.22  MI =  0.45983249703803447  E =  4.0
[[-1 -

 [-1  1 -1  1]]
 
a =  0.29000000000000004  b =  0.42000000000000004  MI =  0.4385461049663463  E =  4.0
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [-1  1  1  1]
 [-1  1 -1  1]]
 
a =  0.3  b =  0.39  MI =  0.3615850329466632  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [-1  1  1  1]
 [-1  1 -1  1]]
 
a =  0.3  b =  0.4  MI =  0.42904940554533133  E =  4.0
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [-1  1  1  1]
 [-1  1 -1  1]]
 
a =  0.31  b =  0.37  MI =  0.3552432679478492  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [-1  1  1  1]
 [-1  1 -1  1]]
 
a =  0.31  b =  0.38  MI =  0.42195797777370025  E =  4.0
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [-1  1  1  1]
 [-1  1 -1  1]]
 
a =  0.32  b =  0.35000000000000003  MI =  0.3513928661560136  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [-1  1  1  1]
 [-1  1 -1  1]]
 
a =  0.32  b =  0.36000000000000004  MI =  0.4173168107445079  E =  4.0
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [-1  1  1  1]
 [-1  1 -1  1]]
 
a =  0.33  b =  0.33  MI =  0.3500939883901443  E =  3.92
[[-1 -1  1  1]
 [ 1  1

 [ 1 -1  1 -1]]
 
a =  0.42000000000000004  b =  0.15000000000000002  MI =  0.47172403470071217  E =  3.920000000000001
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [-1  1  1  1]
 [ 1 -1  1 -1]]
 
a =  0.22  b =  0.55  MI =  0.4980415648642489  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.23  b =  0.53  MI =  0.4727801509299966  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.24000000000000002  b =  0.51  MI =  0.449862734976893  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.25  b =  0.49  MI =  0.4292797287290896  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.25  b =  0.5  MI =  0.5  E =  4.0
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.26  b =  0.47000000000000003  MI =  0.4110292239471327  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [-1  1 -1  1]]
 
a =  0.26  b =  0.48000000000000004  MI =  0.4811544640047982  E =  4.0
[[-1 -1

[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]]
 
a =  0.36000000000000004  b =  0.27  MI =  0.36230943684787736  E =  3.920000000000001
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]]
 
a =  0.36000000000000004  b =  0.28  MI =  0.4245491894398694  E =  4.0
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]]
 
a =  0.37  b =  0.25  MI =  0.3721033482343793  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]]
 
a =  0.37  b =  0.26  MI =  0.43325362750738217  E =  4.0
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]]
 
a =  0.38  b =  0.23  MI =  0.384987970335513  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]]
 
a =  0.38  b =  0.24000000000000002  MI =  0.4449597206154776  E =  4.0
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]]
 
a =  0.39  b =  0.21000000000000002  MI =  0.4011441997213686  E =  3.92
[[-1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]]
 
a =  0.39  b =  0.2

[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.29000000000000004  b =  0.42000000000000004  MI =  0.4385461049663463  E =  4.0
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.3  b =  0.39  MI =  0.3615850329466632  E =  3.92
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.3  b =  0.4  MI =  0.42904940554533133  E =  4.0
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.31  b =  0.37  MI =  0.3552432679478492  E =  3.92
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.31  b =  0.38  MI =  0.42195797777370025  E =  4.0
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.32  b =  0.35000000000000003  MI =  0.3513928661560136  E =  3.92
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.32  b =  0.36000000000000004  MI =  0.4173168107445079  E =  4.0
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]
 [ 1 -1 -1  1]]
 
a =  0.33  b =  0.33  MI =  0.35009

[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [ 1 -1  1  1]
 [-1  1  1 -1]]
 
a =  0.42000000000000004  b =  0.15000000000000002  MI =  0.47172403470071217  E =  3.920000000000001
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [ 1 -1  1  1]
 [-1  1  1 -1]]
 
a =  0.22  b =  0.55  MI =  0.4980415648642489  E =  3.92
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.23  b =  0.53  MI =  0.4727801509299966  E =  3.92
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.24000000000000002  b =  0.51  MI =  0.449862734976893  E =  3.92
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.25  b =  0.49  MI =  0.4292797287290896  E =  3.92
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.25  b =  0.5  MI =  0.5  E =  4.0
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.26  b =  0.47000000000000003  MI =  0.4110292239471327  E =  3.92
[[-1 -1 -1 -1]
 [ 1  1  1 -1]
 [ 1 -1  1  1]
 [ 1 -1 -1  1]]
 
a =  0.26  b =  0.4800000000000000

[[-1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]]
 
a =  0.26  b =  0.01  MI =  0.4110292239471329  E =  3.92
[[-1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]]
 
a =  0.27  b =  0.01  MI =  0.3951169547419021  E =  3.92
[[-1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]]
 
a =  0.28  b =  0.01  MI =  0.3815564110994357  E =  3.92
[[-1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]]
 
a =  0.29000000000000004  b =  0.01  MI =  0.3703691092926814  E =  3.92
[[-1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]]
 
a =  0.3  b =  0.01  MI =  0.36158503294666333  E =  3.92
[[-1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]]
 
a =  0.31  b =  0.01  MI =  0.35524326794784933  E =  3.92
[[-1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]]
 
a =  0.32  b =  0.01  MI =  0.35139286615601373  E =  3.92
[[-1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1  1  1 -1]]
 
a =  0.33  b =  0.01  MI =  0.3500939883901444  E =  3.92
[[-1  1 -1 -1]


Process ForkPoolWorker-20:
Traceback (most recent call last):
Process ForkPoolWorker-23:
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
Process ForkPoolWorker-24:
Process ForkPoolWorker-17:
Process ForkPoolWorker-21:
Process ForkPoolWorker-19:
Process ForkPoolWorker-18:
Process ForkPoolWorker-22:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
Traceback (most recent call last):
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
Traceback (most recent call last):
T

KeyboardInterrupt: 

  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "<ipython-input-12-69fec0c190b5>", line 14, in calculateViolation
    Xy += arr[i,1]*arr[i,2]*pArr[i,2]
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
KeyboardInterrupt
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/vijey/anaconda3/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target