In [22]:
import math
import itertools
import numpy as np
import multiprocessing
from multiprocessing import Process, Pool, Array
from tqdm import tqdm
import time
import matplotlib.pyplot as plt

In [23]:
def probDist(p):
    a = (1-2*p)/2
    b = p

    pArr = np.array([[a,b,a,b],
                 [b,a,a,b],
                 [b,a,b,a],
                 [a,b,b,a]])
    return pArr

In [24]:
def mutualInfo(p):
    return 2 - ((1-2*p)*(1-math.log2(1-2*p))-2*p*math.log2(p))

In [25]:
viol = []
maximalViol = []
def calculateViolation(arr):
    pArr = probDist(0.2498)
    xy = 0
    xY = 0
    Xy = 0
    XY = 0
    for i in range(0, arr.shape[1]):
        xy += arr[0,i]*arr[2,i]*pArr[0,i]
        xY += arr[0,i]*arr[3,i]*pArr[1,i]
        Xy += arr[1,i]*arr[2,i]*pArr[2,i]
        XY += arr[1,i]*arr[3,i]*pArr[3,i]
    E = xy + xY +Xy - XY
    viol.append(abs(2-abs(E)))
    if(abs(2-abs(E)) == 2.0):
            #print("P = ",p, " Setting = ", arr)
            maximalViol.append(arr)

In [26]:
values = [-1,1]
seq = itertools.product(values, repeat=16)
for s in seq:
    # convert to numpy array and reshape to 4x4
    settingArray = np.fromiter(s, np.int8).reshape(4, 4)
    calculateViolation(settingArray)

In [27]:
len(maximalViol)

9216

In [29]:
for arr in maximalViol:
    print(arr)
    print(" ")

[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1  1  1]
 [-1 -1 -1 -1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1  1  1]
 [-1 -1  1  1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1  1  1]
 [-1  1 -1  1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1  1  1]
 [ 1 -1  1 -1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1  1  1]
 [ 1  1 -1 -1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1 -1  1  1]
 [ 1  1  1  1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1 -1  1]
 [-1 -1 -1 -1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1 -1  1]
 [-1 -1  1  1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1 -1  1]
 [-1  1 -1  1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1 -1  1]
 [ 1  1 -1 -1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1 -1  1]
 [ 1  1  1  1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [-1 -1 -1 -1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [-1 -1  1  1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [-1  1 -1  1]]
 
[[-1 -1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]
 [ 1 -1  1

 [-1 -1  1 -1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1  1 -1]
 [ 1 -1 -1 -1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1 -1  1  1]
 [ 1 -1  1 -1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1  1 -1 -1]
 [-1 -1 -1  1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1  1 -1 -1]
 [-1  1 -1 -1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1  1 -1  1]
 [-1 -1  1  1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1  1 -1  1]
 [-1  1  1 -1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1  1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1  1 -1  1]
 [ 1  1 -1 -1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1  1  1 -1]
 [-1 -1 -1 -1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1  1  1  1]
 [-1 -1  1 -1]]
 
[[-1 -1 -1  1]
 [ 1 -1  1  1]
 [ 1  1  1  1]
 [ 1 -1 -1 -1]]
 
[[-1 -1 -1  1]
 [ 1  1 -1 -1]
 [-1 -1 -1 -1]
 [-1  1  1 -1]]
 
[[-1 -1 -1  1]
 [ 1  1 -1 -1]
 [-1 -1 -1 -1]
 [ 1 -1  1 -1]]
 
[[-1 -1 -1  1]
 [ 1  1 -1 -1]
 [-1 -1 -1 -1]
 [ 1  1  1  1]]
 
[[-1 -1 -1  1]
 [ 1  1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]]
 
[[-1 -1 -1  1]
 [ 1  1 -1 -1]
 [-1 -1

 [-1 -1  1  1]]
 
[[-1 -1  1  1]
 [ 1 -1 -1  1]
 [ 1  1  1 -1]
 [-1  1  1 -1]]
 
[[-1 -1  1  1]
 [ 1 -1 -1  1]
 [ 1  1  1  1]
 [-1 -1 -1  1]]
 
[[-1 -1  1  1]
 [ 1 -1 -1  1]
 [ 1  1  1  1]
 [-1  1 -1 -1]]
 
[[-1 -1  1  1]
 [ 1 -1 -1  1]
 [ 1  1  1  1]
 [ 1 -1  1  1]]
 
[[-1 -1  1  1]
 [ 1 -1 -1  1]
 [ 1  1  1  1]
 [ 1  1  1 -1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1 -1 -1 -1]
 [-1  1 -1 -1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1 -1 -1 -1]
 [ 1  1 -1  1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1 -1 -1  1]
 [-1 -1 -1 -1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1 -1 -1  1]
 [-1  1  1 -1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1 -1 -1  1]
 [ 1 -1 -1  1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1 -1 -1  1]
 [ 1  1  1  1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1 -1  1 -1]
 [ 1  1 -1 -1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1 -1  1  1]
 [ 1 -1 -1 -1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1 -1  1  1]
 [ 1  1  1 -1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1  1 -1 -1]
 [-1  1 -1  1]]
 
[[-1 -1  1  1]
 [ 1 -1  1 -1]
 [-1  1

 [-1  1  1 -1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1 -1]
 [ 1  1  1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1  1]
 [-1 -1 -1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1  1]
 [-1  1 -1 -1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1 -1  1  1]
 [ 1  1 -1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1  1 -1 -1]
 [-1 -1 -1 -1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1  1 -1 -1]
 [ 1  1 -1 -1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1 -1 -1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1 -1]
 [ 1  1  1 -1]
 [ 1  1 -1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1  1]
 [-1 -1 -1 -1]
 [-1 -1  1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1  1]
 [-1 -1 -1 -1]
 [ 1  1  1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1  1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1  1]
 [-1 -1  1 -1]
 [-1  1  1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1  1]
 [-1 -1  1  1]
 [-1 -1  1  1]]
 
[[-1  1 -1  1]
 [ 1 -1 -1  1]
 [-1 -1

 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1 -1  1]
 [-1 -1  1 -1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1 -1  1]
 [-1  1 -1 -1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1 -1  1]
 [-1  1  1  1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1 -1  1]
 [ 1 -1  1  1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1 -1  1]
 [ 1  1 -1  1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1  1 -1]
 [-1 -1  1 -1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1  1 -1]
 [-1  1 -1 -1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1  1 -1]
 [-1  1  1  1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1  1 -1]
 [ 1 -1 -1 -1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1  1 -1]
 [ 1 -1  1  1]]
 
[[-1  1  1  1]
 [-1  1  1  1]
 [ 1  1  1 -1]
 [ 1  1 -1  1]]
 
[[-1  1  1  1]
 [ 1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1 -1 -1  1]]
 
[[-1  1  1  1]
 [ 1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1 -1  1 -1]]
 
[[-1  1  1  1]
 [ 1 -1 -1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]]
 
[[-1  1  1  1]
 [ 1 -1 -1 -1]
 [-1 -1 -1  1]
 [ 1 -1 

 [-1  1 -1  1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1 -1  1]
 [ 1  1 -1 -1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1 -1  1]
 [ 1  1  1  1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1  1 -1]
 [-1 -1 -1 -1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1  1 -1]
 [-1 -1  1  1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1  1 -1]
 [-1  1 -1  1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1  1 -1]
 [ 1 -1  1 -1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1  1 -1]
 [ 1  1 -1 -1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [-1  1  1 -1]
 [ 1  1  1  1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]
 [-1 -1 -1 -1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]
 [-1 -1  1  1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]
 [-1  1 -1  1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]
 [ 1 -1  1 -1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]
 [ 1  1 -1 -1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [ 1 -1 -1  1]
 [ 1  1  1  1]]
 
[[ 1 -1 -1  1]
 [-1  1  1 -1]
 [ 1 -1

 [ 1  1 -1  1]]
 
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1 -1  1  1]
 [ 1  1  1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1  1 -1  1]
 [-1 -1 -1  1]]
 
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1  1 -1  1]
 [-1 -1  1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1  1 -1  1]
 [-1  1  1  1]]
 
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1  1 -1  1]
 [ 1 -1 -1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1  1 -1  1]
 [ 1  1 -1  1]]
 
[[ 1 -1  1  1]
 [-1  1 -1 -1]
 [ 1  1 -1  1]
 [ 1  1  1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1  1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1  1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1  1]
 [-1 -1  1 -1]
 [ 1  1  1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1  1]
 [-1 -1  1  1]
 [-1 -1 -1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1  1]
 [-1 -1  1  1]
 [-1  1  1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1  1]
 [-1 -1  1  1]
 [ 1  1 -1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1  1]
 [-1  1 -1 -1]
 [-1 -1  1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1  1]
 [-1  1 -1 -1]
 [ 1 -1 -1 -1]]
 
[[ 1 -1  1  1]
 [-1  1 -1  1]
 [-1  1

 [ 1 -1  1 -1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1 -1  1]
 [-1 -1 -1  1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1 -1  1]
 [-1  1 -1 -1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1 -1  1]
 [-1  1  1  1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1 -1  1]
 [ 1 -1 -1 -1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1 -1  1]
 [ 1 -1  1  1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1 -1  1]
 [ 1  1  1 -1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1  1 -1]
 [-1 -1 -1  1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1  1 -1]
 [-1  1 -1 -1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1  1 -1]
 [-1  1  1  1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1  1 -1]
 [ 1 -1 -1 -1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1  1 -1]
 [ 1 -1  1  1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1 -1  1 -1]
 [ 1  1  1 -1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1  1 -1 -1]
 [-1 -1 -1  1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1  1 -1 -1]
 [-1  1 -1 -1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1  1 -1 -1]
 [-1  1  1  1]]
 
[[ 1  1 -1  1]
 [-1 -1  1 -1]
 [-1  1

 [-1 -1 -1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1 -1  1  1]
 [ 1 -1  1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1 -1  1  1]
 [ 1  1 -1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1 -1 -1]
 [-1 -1  1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1 -1 -1]
 [-1  1 -1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1 -1 -1]
 [ 1  1  1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1 -1  1]
 [-1 -1 -1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1 -1  1]
 [ 1 -1  1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1 -1  1]
 [ 1  1 -1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1  1 -1]
 [-1 -1  1  1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1  1 -1]
 [-1  1 -1  1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1  1 -1]
 [ 1  1  1  1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1  1  1]
 [-1 -1 -1  1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1  1  1]
 [ 1 -1  1  1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [-1  1  1  1]
 [ 1  1 -1  1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [ 1 -1 -1 -1]
 [-1 -1  1 -1]]
 
[[ 1  1  1 -1]
 [ 1  1  1  1]
 [ 1 -1